[package]
name = "file-rotate"
version = "0.8.0"
authors = ["Kevin Robert Stravers <kevin@stravers.net>", "Erlend Langseth <3rlendhl@gmail.com>"]
edition = "2018"
description = "Log rotation for files"
homepage = "https://github.com/kstrafe/file-rotate"
repository = "https://github.com/kstrafe/file-rotate"
keywords= ["log", "rotate", "logrotate"]
license = "MIT"

[lib]
path = "src/lib.rs"

[dependencies]


[dev-dependencies]
tempfile = "3"
